/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as ReferralRouteImport } from './routes/referral'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as QuizResultsRouteImport } from './routes/quiz.results'
import { Route as NotesIdRouteImport } from './routes/notes.$id'
import { Route as DiscussionTopicRouteImport } from './routes/discussion.$topic'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralRoute = ReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRoute,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotesRoute,
} as any)
const QuizResultsRoute = QuizResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizRoute,
} as any)
const NotesIdRoute = NotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotesRoute,
} as any)
const DiscussionTopicRoute = DiscussionTopicRouteImport.update({
  id: '/discussion/$topic',
  path: '/discussion/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRouteWithChildren
  '/referral': typeof ReferralRoute
  '/revision': typeof RevisionRoute
  '/subscription': typeof SubscriptionRoute
  '/tasks': typeof TasksRoute
  '/verify': typeof VerifyRoute
  '/discussion/$topic': typeof DiscussionTopicRoute
  '/notes/$id': typeof NotesIdRoute
  '/quiz/results': typeof QuizResultsRoute
  '/notes/': typeof NotesIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/referral': typeof ReferralRoute
  '/revision': typeof RevisionRoute
  '/subscription': typeof SubscriptionRoute
  '/tasks': typeof TasksRoute
  '/verify': typeof VerifyRoute
  '/discussion/$topic': typeof DiscussionTopicRoute
  '/notes/$id': typeof NotesIdRoute
  '/quiz/results': typeof QuizResultsRoute
  '/notes': typeof NotesIndexRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notes': typeof NotesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRouteWithChildren
  '/referral': typeof ReferralRoute
  '/revision': typeof RevisionRoute
  '/subscription': typeof SubscriptionRoute
  '/tasks': typeof TasksRoute
  '/verify': typeof VerifyRoute
  '/discussion/$topic': typeof DiscussionTopicRoute
  '/notes/$id': typeof NotesIdRoute
  '/quiz/results': typeof QuizResultsRoute
  '/notes/': typeof NotesIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/contact'
    | '/home'
    | '/leaderboard'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/referral'
    | '/revision'
    | '/subscription'
    | '/tasks'
    | '/verify'
    | '/discussion/$topic'
    | '/notes/$id'
    | '/quiz/results'
    | '/notes/'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/contact'
    | '/home'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/referral'
    | '/revision'
    | '/subscription'
    | '/tasks'
    | '/verify'
    | '/discussion/$topic'
    | '/notes/$id'
    | '/quiz/results'
    | '/notes'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/contact'
    | '/home'
    | '/leaderboard'
    | '/notes'
    | '/notifications'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/referral'
    | '/revision'
    | '/subscription'
    | '/tasks'
    | '/verify'
    | '/discussion/$topic'
    | '/notes/$id'
    | '/quiz/results'
    | '/notes/'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  HomeRoute: typeof HomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NotesRoute: typeof NotesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuizRoute: typeof QuizRouteWithChildren
  ReferralRoute: typeof ReferralRoute
  RevisionRoute: typeof RevisionRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TasksRoute: typeof TasksRoute
  VerifyRoute: typeof VerifyRoute
  DiscussionTopicRoute: typeof DiscussionTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referral': {
      id: '/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof ReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/notes/': {
      id: '/notes/'
      path: '/'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof NotesRoute
    }
    '/quiz/results': {
      id: '/quiz/results'
      path: '/results'
      fullPath: '/quiz/results'
      preLoaderRoute: typeof QuizResultsRouteImport
      parentRoute: typeof QuizRoute
    }
    '/notes/$id': {
      id: '/notes/$id'
      path: '/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof NotesIdRouteImport
      parentRoute: typeof NotesRoute
    }
    '/discussion/$topic': {
      id: '/discussion/$topic'
      path: '/discussion/$topic'
      fullPath: '/discussion/$topic'
      preLoaderRoute: typeof DiscussionTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NotesRouteChildren {
  NotesIdRoute: typeof NotesIdRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

const NotesRouteChildren: NotesRouteChildren = {
  NotesIdRoute: NotesIdRoute,
  NotesIndexRoute: NotesIndexRoute,
}

const NotesRouteWithChildren = NotesRoute._addFileChildren(NotesRouteChildren)

interface QuizRouteChildren {
  QuizResultsRoute: typeof QuizResultsRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizResultsRoute: QuizResultsRoute,
  QuizIndexRoute: QuizIndexRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  HomeRoute: HomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  NotesRoute: NotesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  QuizRoute: QuizRouteWithChildren,
  ReferralRoute: ReferralRoute,
  RevisionRoute: RevisionRoute,
  SubscriptionRoute: SubscriptionRoute,
  TasksRoute: TasksRoute,
  VerifyRoute: VerifyRoute,
  DiscussionTopicRoute: DiscussionTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
